# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moderation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'moderation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10moderation.proto\x12\nmoderation\"5\n\x0c\x43heckRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x11\n\tfile_name\x18\x02 \x01(\t\"0\n\rCheckResponse\x12\x0f\n\x07is_safe\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t2V\n\x11ModerationService\x12\x41\n\nCheckImage\x12\x18.moderation.CheckRequest\x1a\x19.moderation.CheckResponseB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moderation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_CHECKREQUEST']._serialized_start=32
  _globals['_CHECKREQUEST']._serialized_end=85
  _globals['_CHECKRESPONSE']._serialized_start=87
  _globals['_CHECKRESPONSE']._serialized_end=135
  _globals['_MODERATIONSERVICE']._serialized_start=137
  _globals['_MODERATIONSERVICE']._serialized_end=223
# @@protoc_insertion_point(module_scope)
